include:
  - board: xiao_ble
    shield: totem_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: totem_right rgbled_adapter
  - board: xiao_ble
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
