CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_BT_CTLR_TX_PHY_2M=n
#CONFIG_ZMK_BOARD_COMPAT=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000 
# Optional: Lower idle timeout (default is 1000ms)
CONFIG_ZMK_IDLE_TIMEOUT=30000


CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
